### ISSUE TITLE
FR: Custom Light Guide as KK alternative.

### ISSUE THREAD

**Issue by p33k** [tillt/KompleteSynthesia#11]
As KK control currently is a mess running native on Silicon Macs and within Logic. 
Is it possible to modify your code to provide a KK "alternative"?

The most important part for me in the NKS ecosystem is the light guide. beeing able to see key switches and key ranges especially in orchestra librarys is awesome.
sadly the implementation for the light guide seems to be a lot of work for plugin developers and because of bugs in KK it doesn't work well.

Running a new MacBook with M2 Max, Logic Pro even crashes and runs unstable with KK and only NI Instruments.
When I run them in Kontakt instead everything is going smooth. but then the Lightguide is missing.

Third partys products are problematic as well, as a lot of NKS files still only support the vst2 version that is dropped in KK for Native Mac.
For instance ReFX Nexus light guide isn't working in Logic as well as all East West Opus instruments currently.

KK slowing down the system and don't working properly makes an alternative more urgent then ever.
with your code base for the light guide it should be possible to build something that enables us users to optimize the support ourselves, when the manufacturers simple don't do it or need years to implement it.

**Comment by tillt** [comment]
Thanks for posting this idea first and foremost. Sorry for my tardy reply, my day job is currently demanding everything.

What I understand is that you (just like everyone else) hates the experience on apple silicon that native instruments is currently offering. I truly share your sentiment when it comes to rage boiling up whenever we see either a crash or a stupid: "sorry, dont support this on your machine". 

I also understand that the home production boom had wound down and thus companies like NI are in rough waters these days. Additional to the economic situation, the sheer number of software products that NI is offering under the hood of their controllers is mind boggling. Supporting those codebases must be absolute hell. This leads me to warm feelings for those poor devs struggling to keep that zoo of products maintained.

Back to the core of your idea which I still did not fully get -- forgive me, I am not a pro user of the NI ecosystem.

What I do understand is that you want an app that provides the visual information of key maps and key presses using the lightguide feature. What I do not understand yet is; where that app should receive the information from that tells it about key maps?

**Comment by p33k** [comment]
Regarding the NI situation: I would say it's rage, hate or even anger, but it's just said to see the great hardware and ecosystem not using it's full potential.
I feel with the developers as well and can understand that maintaining this huge amount of different software/hardware is a lot of work. and apple coming up with the silicon platform, third party compatibility and so on is just crazy.

but waiting for NI to realize feature requests or bug fixes can takes decades as one can see in the NI forum.

------------------------------------------------------------------------------------------
about the idea to "bypass" the Komplete Kontrol software:
yea the "how will the app know which light guide preset to use" would be the tricky part I guess.

current situation:
If i want to use East West Orchestra for example right now native with apple silicon I have this options:

1. run their Opus Software within Komplete Kontrol.au in Logic. doing this will get --> low performance, no Light Guide (only works with vst2 Version under Rosetta currently, because the NKS presets and Light Guide code doesn't support VST3 currently), the KK Kontrol browser doesn't work because of the same reason.
2. run Opus directly --> again no Light Guide support.
2.1 there is a workaround to setup custom light guide via Midi Presets in Komplete Kontrol standalone and choose the presets later on the keyboard when runnning logic. But there is no way to choose the presets automatically, and no way to group or filter them.
so I you have an orchestra template with 50 instruments with different keyranges and keyswitches u want to see on the Komplete Kontrol Keyboard. u have to click through all presets each time you choose a different track in logic.
so thats not really an option.


one idea would be to use some other VST wrapper like New Sonic Arts Freestyle. and have a **separate VST plugins** that outputs chosen preset data to the custom Komplete Kontrol app.

So we would need 2 apps:
1. "Custom Komplete Kontrol" - which is basically your app. there u could save presets with light guide setups.
2. "Preset submitter VST" - a "simple" VST that sends bank and preset oupt to the "Custom Komplete Kontrol" app.

so one would choose Logic --> Instrument Track --> Wrapper "Freestyle" 
in Freestyle have East West OPUS + "Preset submitter VST". in that vst u could choose bank 1 preset 1 for example which will be "sent" to the custom Komplete Kontrol app.

Then one would for example generate a bank 1 "East West Strings" in the "Custom Komplete Kontrol" app and a patch 1 "11 Violins master". in that preset u can choose which keys should light in which color and maybe a custom picture which is shown on the KK display.

in the "preset submitter you could choose "bank 1 preset 1". and then this would be submitted to the "Custom Komplete Kontrol"

more complex would be to implement the "scale lightning" while having the custom light guide...
