### ISSUE TITLE
USB Error: (iokit/common) exclusive access and device already open

### ISSUE THREAD

**Issue by apexJCL** [tillt/KompleteSynthesia#9]
**System information:**
- macOS Ventura v13.0.1
- Apple M1 Pro

<img width="249" alt="Screenshot 2023-02-04 at 12 14 48" src="https://user-images.githubusercontent.com/4037632/216787944-b8f466d8-150b-493a-a9fb-688b1106b75a.png">

I get this error whenever I try to launch the application after the setup screens.
I've tried removing the app but to no avail.

Any clues/suggestions?

**Comment by tillt** [comment]
Are you running the latest version of Komplete Synthesia (v0.50 release)?

**Comment by apexJCL** [comment]
Yes, latest version, sorry I forgot to mention that.

**Comment by tillt** [comment]
I did in fact already find at least one bug in the relevant code by now - namely the NTKDaemon would not be treated correctly.  Is it by any chance that one that is running on your machine and blocks access? 

```
ps aux |grep NIHardware

ps aux |grep NIHost

ps aux |grep NTK

```

Please let me know what those commands did when run in your Terminal.app.

**Comment by apexJCL** [comment]
It seems there's both NIHardware and NIHostIntegrationAgent processes running in the background:

```
➜  ~ ps aux |grep NIHardware

ps aux |grep NIHost

ps aux |grep NTK

carlos             636   0.0  0.1 409942544  22240   ??  S    Sat11AM   0:05.60 /Library/Application Support/Native Instruments/Hardware/NIHardwareAgent.app/Contents/MacOS/NIHardwareAgent
carlos           36039   0.0  0.0 408626880   1296 s000  S+    7:40AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox NIHardware
carlos             632   0.0  0.2 409946528  29136   ??  S    Sat11AM   0:56.89 /Library/Application Support/Native Instruments/Hardware/NIHostIntegrationAgent.app/Contents/MacOS/NIHostIntegrationAgent
carlos           36041   0.0  0.0 408626880   1296 s000  S+    7:40AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox NIHost
carlos           36043   0.0  0.0 408626880   1296 s000  S+    7:40AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox NTK
```

**Comment by tillt** [comment]
Those are the problem - if you killed them manually
```
killall -9 NIHardwareAgent
killall -9 NIHostIntegrationAgent
```
then restart KompleteSynthesia -> it should be better now.

Now question is why they dont get killed by KompleteSynthesia as intended? Guess I need to do some more research...

**Comment by tillt** [comment]
Also, please give 0.51 a try - some changes in there that might do the trick for you - without manual intervention.

**Comment by apexJCL** [comment]
I had to manually kill both processes but after doing so, it worked!

Thanks for the quick response ❤️

**Comment by tillt** [comment]
Glad that worked.

With 0.51, when starting without doing anything extra, what happens? I wonder if that process killing and waiting for it to be truly gone was doing the job now or not.

**Comment by apexJCL** [comment]
It is not waiting for the process to be killed, it just throws the same error as before.

I'm not too familiar with Objective-C so I can't help (for now).

**Comment by tillt** [comment]
Really, the same error? 
So it says "exclusive access..." blah --- it does NOT say "Failed to terminate ..."?

**Comment by apexJCL** [comment]
https://user-images.githubusercontent.com/4037632/217296545-49598ba9-4534-4bd0-9a03-88298295680e.mp4

**Comment by tillt** [comment]
oh wow - that is very helpful indeed - I had not considered it behaving like that. We are onto something....

**Comment by tillt** [comment]
@apexJCL please give 0.52 a shot - I may have identified the problem...

**Comment by apexJCL** [comment]
Just tested and everything seems to be working just fine (both at open and closing the app).

Excellent work, highly appreciated 🙏🏼
